/*
 * Copyright (C) 2015-2018, STMicroelectronics - All Rights Reserved
 *
 * SPDX-License-Identifier:	GPL-2.0+	BSD-3-Clause
 *
 */

/*
 * File generated by STMicroelectronics STM32CubeMX DDR Tool for MPUs
 */

/*
 *
 * Device tree generated from STM32CubeMX project without DDR IP correctly configured.
 * If you need the DDR configuration to be part of your device tree, ensure you have proper
 * DDR ip configuration in your STM32CubeMX project and generate device tree.
 *
 */


